# Generated by Django 5.2.7 on 2025-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
