# Generated by Django 5.2.7 on 2025-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_examplemodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
