# Generated by Django 5.2.7 on 2025-10-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_examplemodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
